# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'figure_paint.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class FigurePainter(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(FigurePainter, self).__init__(parent)
        self.resize(837, 606)
        self.setupUi()

    def setupUi(self):
        self.tableView = QtWidgets.QTableWidget()
        self.tableView.setObjectName("Form")
        self.tableView.setGeometry(QtCore.QRect(10, 10, 451, 581))
        self.tableView.setObjectName("tableView")

        self.groupBox = QtWidgets.QGroupBox()
        self.groupBox.setGeometry(QtCore.QRect(480, 10, 331, 251))
        self.groupBox.setObjectName("groupBox")

        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(90, 30, 91, 21))
        self.comboBox.setObjectName("comboBox")

        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")


        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(90, 60, 91, 21))
        self.spinBox.setObjectName("spinBox")

        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 55, 16))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 55, 16))
        self.label_2.setObjectName("label_2")

        self.groupBox_2 = QtWidgets.QGroupBox()
        self.groupBox_2.setGeometry(QtCore.QRect(480, 270, 341, 321))
        self.groupBox_2.setObjectName("groupBox_2")

        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setGeometry(QtCore.QRect(0, 20, 331, 291))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Parameter Panel"))
        self.comboBox.setItemText(0, _translate("Form", "\\n"))
        self.comboBox.setItemText(1, _translate("Form", ","))
        self.comboBox.setItemText(2, _translate("Form", ";"))
        self.comboBox.setItemText(3, _translate("Form", " "))
        self.comboBox.setItemText(4, _translate("Form", ":"))
        self.label.setText(_translate("Form", "Spliter"))
        self.label_2.setText(_translate("Form", "Gap Line"))
        self.groupBox_2.setTitle(_translate("Form", "GroupBox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = FigurePainter()
    ui.show()
    sys.exit(app.exec_())
